### ISSUE TITLE
Feature request: Ability to cancel the deal proposal before accepted

### ISSUE THREAD

**Issue by nicola** [protocol/retrieval-pinning#72]
* Client signs the tx to store the file, tx goes on chain
* Provider is taking too long to accept the deal
* Client cancels the deal

We need a way in the UX to do so.

**Comment by turinglabsorg** [comment]
This feature was in the original project, @Steve-Rog please make sure to have it again in the UI, wait for @0xjona to be sure how and where implement it from an UX/Graphic side.

**Comment by 0xjona** [comment]
Yes @claudiofabbro was already aware of the missing feature, will be updated asap

**Comment by turinglabsorg** [comment]
@nicola closing, this feature is now available.
